title: EKA2L1
email: cc@12z1.com
description:
  An Experimental Symbian OS Emulator
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://12z1.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  EKA2L1

languages: [ "en", "vi" ]
exclude_from_localization: ["assets", "CNAME"]
defaultLang: en
languageNames:
  en: English
  vi: Tiếng Việt

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
   
footer:
  links:
    - label: Github
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eka2l1/eka2l1"
    - label: Youtube
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/channel/UCCdPQT6Le2xw_z9cutkVwyA"
    - label: Mail
      icon: "fas fa-envelope"
      url: "mailto:cc@12z1.com"

# Github
username: EKA2L1
repo: eka2l1.github.io
branch: main

source: .
destination: _site

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
